services:
  backend:
    build: ./backend
    container_name: doc_app_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: doc_app_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
